Fabric 2.x chaincode lifecycle update
hyperledger-labs/blockchain-automation-framework pull request #1041
Opened 2020-09-17 06:35 UTC by himanshulalarya

**Changelog**
- Updated version changes and chaincode lifecycle for fabric 2.x
- Added new chart for chaincode approve
- Updated Fabric Binaries

 

**Reviewed by**
@lakshyakumar @jagpreetsinghsasan 

 

**Linked issue**
#966 #963

2020-09-17 08:04 UTC, suvajit-sarkar commented on platforms/hyperledger-fabric/configuration/roles/create/chaincode/commit/tasks/write.yaml
> +    VAULT_TOKEN: "{{ vault.root_token }}"
new line please

2020-09-17 08:06 UTC, suvajit-sarkar commented on platforms/shared/configuration/roles/helm_lint/vars/main.yaml
> +
additional newline might be the reason of linting error in molecule, run the molecule test and fix the errors

2020-09-17 09:00 UTC, sownak requested changes

2020-09-17 09:00 UTC, sownak commented on platforms/hyperledger-fabric/configuration/roles/helm_component/templates/cli.tpl
> +      address: {{ peer.name }}.{{ component_ns }}.{{ external_url_suffix }}:8443
refer comments in PR #1040

2020-09-17 09:02 UTC, sownak commented on platforms/hyperledger-fabric/charts/create_channel/templates/create_channel.yaml
> +              if [ $.Values.metadata.network.version == '1.4.4']
Why 1.4.4 and not 1.4.8?

2020-09-17 09:38 UTC, jagpreetsinghsasan requested changes
If there are changes done to network.yaml, then change the sample network.yaml as well

2020-09-18 06:47 UTC, himanshulalarya commented
Creating a new pr for this issue as some checks were not signed

2020-09-18 06:47 UTC, closed without merging