[ Fabric ] Adding the support of upgarding chaincode for Fabric 2.2
hyperledger-labs/blockchain-automation-framework pull request #1144
Opened 2020-10-30 05:02 UTC by lakshyakumar

Signed-off-by: lakshyakumar <lakshya.kumar@accenture.com>

**Changelog**
- Add the support of upgarding chaincode for Fabric 2.2 using `chaincode-install-instantiate.yaml` playbook
- Fix the comments in the playbooks.
- Update operational guide for upgarding the chaincode in Fabric.

 

**Reviewed by**
@jagpreetsinghsasan 

 

**Linked issue**
#1133

2020-10-30 09:31 UTC, jagpreetsinghsasan approved these changes

2020-10-30 11:17 UTC, sownak requested changes

2020-10-30 11:17 UTC, sownak commented on platforms/hyperledger-fabric/configuration/chaincode-upgrade.yaml
> +# 1. Upgrades the chaincode provided in network.yaml from each peer (for fabric version less than 2.2.0 )
rather mention 1.4.x

2020-10-30 11:17 UTC, sownak commented on platforms/hyperledger-fabric/configuration/chaincode-install-instantiate.yaml
>  # 2. Instantiates chaincode from the creator participant peer of the channel( For Fabric 1.4)
remove 1.4 from here or make the comments better for 1.4.x and 2.2.x

2020-10-30 11:17 UTC, sownak commented on docs/source/operations/upgrading_chaincode.md
> +## Run playbook for Fabric versions less than 2.2.0
1.4.x not less than 2.2.0

2020-10-30 11:17 UTC, sownak commented on docs/source/operations/upgrading_chaincode.md
> +  - [Run playbook for Fabric versions less than 2.2.0](#run-playbook-for-fabric-versions-less-than-220)
1.4.x and 2.2.x (as we wont be supporting 2.0.0 anyway)

2020-11-02 09:23 UTC, sownak approved these changes

2020-11-02 09:24 UTC, merged