[feat] Configurable secret path for hasicorp vault
hyperledger-labs/blockchain-automation-framework pull request #1154
Opened 2020-11-05 15:47 UTC by NthMetal

**Changelog**
- Add:
network.yaml configurations for vault can now accept an `secret_path` option. 
This option changes the secret engine used for this vault. If not provided it will default to `secret/`
For below example the vault will use the secret engine `supersecret/`
```
# Hashicorp Vault server address and root-token. Vault should be unsealed.
# Do not check-in root_token
vault:
    url: "vault_addr"
    root_token: "vault_root_token"
    secret_path: "supersecret"
```

This initial commit doesn't contain any documentation changes because I am unsure of the scope.
Since this is optional, should I add it to the example network.yaml files but comment it out? 
```
# Hashicorp Vault server address and root-token. Vault should be unsealed.
# Do not check-in root_token
vault:
    url: "vault_addr"
    root_token: "vault_root_token"
    # secret_path: "vault_secret_path"
```
Is there another place it should be refrenced?

**Reviewed by**
@developer_github_id

 

**Linked issue**
#1153

2020-11-05 18:31 UTC, sownak commented
Thanks for this PR. In the sample network.yaml you can add the default path.

2020-11-05 19:03 UTC, NthMetal commented
done.
Added: 
```
      # Hashicorp Vault server address and root-token. Vault should be unsealed.
      # Do not check-in root_token
      vault:
        url: "vault_addr"
        root_token: "vault_root_token"
        secret_path: "secret"
```

2020-11-06 07:26 UTC, jagpreetsinghsasan requested changes
This looks fine to me.
If you can please update the docs as well incorporating these changes, it will be complete.
For example, the certificate paths in the docs should also mention about this optional path
https://blockchain-automation-framework.readthedocs.io/en/latest/architectureref/certificates_path_list_corda.html

2020-11-09 06:43 UTC, jagpreetsinghsasan commented on docs/source/architectureref/certificates_path_list_corda.md
> +* Optionally, `secret_path` can be set on the network.yaml to change the secret engine from the default `secret/`.
Optionally, `secret_path` can be set on the network.yaml to change the secret engine from the default `secrets/`.

2020-11-09 06:49 UTC, jagpreetsinghsasan approved these changes

2020-11-09 06:59 UTC, merged