[ci skip] Adding indy validator nodes
hyperledger-labs/blockchain-automation-framework pull request #1197
Opened 2020-11-26 09:15 UTC by sauveergoel

Signed-off-by: sauveergoel <sauveer.goel@accenture.com>

**Changelog**
- Added Indy validator nodes 

**Reviewed by**
@suvajit-sarkar @sownak 

**Linked issue**
#986

2020-11-26 09:18 UTC, sauveergoel commented
This PR is WIP, created for peer review.

2020-12-04 07:17 UTC, jagpreetsinghsasan commented
The concern which I have is that, in BAF, helm charts are the logical entities for the platform they are developed for. Thus having chart for 'org' and 'new org' doesn't make any sense. 
What you can do is, have the logic embedded in the 'org' chart itself which can run over a condition check of  `org_status: new/existing` (the org_status tag can be passed to the value file of the 'org' chart)

2020-12-04 10:07 UTC, sownak requested changes

2020-12-04 10:07 UTC, sownak commented on platforms/hyperledger-indy/charts/indy-ledger-txn-new-node/Chart.yaml
> +name: indy-ledger-txn-new-node
Why do we need a new chart for running ledger-txn for a new node? Why can't we use the existing charts?

2020-12-04 10:07 UTC, sownak commented on platforms/hyperledger-indy/charts/indy-node-new/Chart.yaml
> +name: indy-node-new
same comment? why "new" chart is needed.

2020-12-04 10:07 UTC, sownak commented on platforms/hyperledger-indy/configuration/roles/create/helm_component/node/templates/node.tpl
> +        storagesize: 5Gi
does this need so much hard disk by default?

2020-12-04 10:07 UTC, sownak commented on platforms/hyperledger-indy/configuration/roles/setup/add_did_vault/README.md
> +## setup/endorsers
setup/add_did_vault is not correct name, either use setup/did_vault or add/did_vault

2020-12-04 10:07 UTC, sownak commented on platforms/hyperledger-indy/configuration/samples/network-indy-newnode.yaml
> +  # This is a sample configuration file for hyperledger indy which can reused for a sample indy network of 9 nodes.
these comments does not correspond to the sample

2020-12-07 11:07 UTC, jagpreetsinghsasan requested changes

2020-12-07 11:07 UTC, jagpreetsinghsasan commented on docs/source/developer/indy-helmcharts.md
> +|   |-- indy-ledger-txn-new-node
This should be removed

2020-12-07 11:07 UTC, jagpreetsinghsasan commented on docs/source/developer/indy-helmcharts.md
> +|   |-- indy-node-new
This should be removed

2020-12-07 11:07 UTC, jagpreetsinghsasan commented on docs/source/developer/indy-helmcharts.md
> +```
This patch should be removed

2020-12-07 11:07 UTC, jagpreetsinghsasan commented on docs/source/developer/indy-helmcharts.md
> +```
This patch should be removed

2020-12-07 11:07 UTC, jagpreetsinghsasan commented on platforms/hyperledger-indy/configuration/samples/network-indy-newnode.yaml
> +
new line should be there and extra tabbled/spaced lines should be removed from the end

2020-12-07 11:15 UTC, jagpreetsinghsasan approved these changes
LGTM

2020-12-07 12:45 UTC, sownak requested changes

2020-12-07 12:45 UTC, sownak commented on docs/source/developer/indy-ansible.md
> +## **setup/add_did_vault**
Is this role there? I do not see any further reference to this.

2020-12-07 12:45 UTC, sownak commented on docs/source/operations/adding_new_org_indy.md
> +| genesis.type | Flag to derive if the organisation needs to be added to an existing network.|
type is not a flag. It should be called add_org (which should be boolean) and then it should be called a flag. The yaml above does not describe the usage of the so called flag in detail, that must be added as well.

2020-12-07 12:45 UTC, sownak commented on platforms/hyperledger-indy/charts/indy-ledger-txn/templates/job.yaml
> +{{- if ne $.Values.genesis.type "add-org" }}
as above

2020-12-07 12:45 UTC, sownak commented on platforms/hyperledger-indy/charts/indy-node/templates/statefulset.yaml
> +         - name: GENESIS_TYPE
GENESIS_TYPE is wrong because there are no different types of Genesis in Indy

2020-12-07 12:45 UTC, sownak commented on platforms/hyperledger-indy/charts/indy-node/values.yaml
> +  pool:
why is "type" missing here. (Should be replaced by add_org)
Also description of why this parameter is needed is missing.

2020-12-07 12:45 UTC, sownak commented on platforms/hyperledger-indy/configuration/samples/network-indy-newnode.yaml
> +    # Information about pool transaction genesis and domain transactions genesis
Add more details as to what is mandatory and what is not.

2020-12-08 20:09 UTC, sownak approved these changes

2020-12-08 20:09 UTC, merged