Add digitalocean support
hyperledger-labs/blockchain-automation-framework pull request #1260
Opened 2021-01-05 03:40 UTC by sivaramsk

**Changelog**
- Add digitalocean support to BAF Hyperledger Fabric
 

**Reviewed by**
@developer_github_id

 
**Linked issue**
#1219

2021-01-06 10:00 UTC, sownak requested changes

2021-01-06 10:00 UTC, sownak commented on platforms/hyperledger-fabric/configuration/roles/create/storageclass/templates/digitalocean_sc.tpl
> +volumeBindingMode: Immediate
Please add newline

2021-01-06 10:00 UTC, sownak commented on platforms/hyperledger-fabric/configuration/roles/create/storageclass/vars/main.yaml
> +  digitalocean-peer: digitalocean_sc.tpl
please add newline

2021-01-06 10:00 UTC, sownak commented on platforms/hyperledger-fabric/configuration/samples/network-fabric-add-new-channel.yaml
> +      cloud_provider: aws   # Options: aws, azure, gcp, digitalocean, minikube
Add similar change in the docs folder which contains all our readthedocs documentation

2021-01-11 08:40 UTC, suvajit-sarkar approved these changes

2021-01-11 09:33 UTC, sownak approved these changes

2021-01-11 09:33 UTC, merged