Feature/983
hyperledger-labs/blockchain-automation-framework pull request #1274
Opened 2021-01-25 16:56 UTC by ragalz

**Changelog**
- Update deployment to allow DNS on network.yaml

 

**Reviewed by**
@developer_github_id

 

**Linked issue**
#983

2021-01-26 14:57 UTC, sownak requested changes

2021-01-26 14:57 UTC, sownak commented on platforms/hyperledger-fabric/releases/dev/supplychain/orderer/namespace.yaml
> +apiVersion: v1
releases folder should not be checked-in

2021-01-26 14:57 UTC, sownak commented on platforms/shared/charts/ambassador/templates/service.yaml
> +    service.beta.kubernetes.io/aws-load-balancer-type: elb
this should not be changed as it impacts Indy

2021-01-27 04:52 UTC, jagpreetsinghsasan reviewed
Please do not delete the releases/README.md file

2021-01-27 07:31 UTC, suvajit-sarkar approved these changes
incorporate the changes requested by @jagpreetsinghsasan 
reset LGTM

2021-01-27 09:38 UTC, jagpreetsinghsasan approved these changes
LGTM

2021-01-27 10:32 UTC, merged