[fabric] #1314 Fix and test existing molecule scenarios
hyperledger-labs/blockchain-automation-framework pull request #1348
Opened 2021-03-16 10:30 UTC by TonyRowntree

Signed-off-by: TonyRowntree <33454202+TonyRowntree@users.noreply.github.com>

**Changelog**
- Fix molecule scenario Crypto, Default and Pre-Vault-Setup

**Reviewed by**
@sownak 

 

**Linked issue**
#1314

2021-03-18 05:55 UTC, jagpreetsinghsasan requested changes

2021-03-18 05:55 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/molecule/crypto/verify.yml
> +  #- name: Check if the genesis block is created or not
You don't need to comment the code. As this piece of code is irrelevant, you can just remove this piece of code.

2021-03-18 05:55 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/molecule/crypto/verify.yml
> +  #- name: Assert if the genesis block is created or not
You don't need to comment the code. As this piece of code is irrelevant, you can just remove this piece of code.

2021-03-18 05:58 UTC, jagpreetsinghsasan commented
The molecule test failed. Have a look, as in why it failed.

2021-03-22 09:47 UTC, sownak commented
@TonyRowntree I have made some changes so you will need to update your branch with the latest changes from develop

2021-03-22 15:02 UTC, TonyRowntree commented
Have made the changes and fixed issue.

Please review @sownak @jagpreetsinghsasan

2021-03-22 15:26 UTC, sownak approved these changes

2021-03-22 15:26 UTC, merged