added default molecule tests
hyperledger-labs/blockchain-automation-framework pull request #1432
Opened 2021-04-29 09:47 UTC by Dimbu-Afonso

**Changelog**
- Added molecule test for default scenario

 

**Reviewed by**
@suvajit-sarkar @deepakkumardbd @jagpreetsinghsasan 

 

**Linked issue**
#718

2021-04-29 16:24 UTC, suvajit-sarkar requested changes

2021-04-29 16:24 UTC, suvajit-sarkar commented on platforms/quorum/configuration/molecule/default/converge.yml
> +  tasks:
why are these tasks here? these checks should be in verify

2021-05-04 10:31 UTC, sownak requested changes

2021-05-04 10:31 UTC, sownak commented on platforms/quorum/configuration/molecule/default/verify.yml
> +
too many spaces

2021-05-04 10:31 UTC, sownak commented on platforms/quorum/configuration/molecule/default/prepare.yml
> +      url: "http://localhost:9090/ui/"
this wont work as you are not setting up Vault

2021-05-04 13:15 UTC, sownak approved these changes

2021-05-04 14:05 UTC, suvajit-sarkar approved these changes

2021-05-04 14:06 UTC, merged