[fabric] Implemented additional annotations for pods
hyperledger-labs/blockchain-automation-framework pull request #1459
Opened 2021-05-11 11:18 UTC by alvaropicazo

**Changelog**
- Added annotations for ca, ca-tools, peernodes and orderernodes.
- Added annotations section for network fabric templates
- Updated charts, helm files for reading those annotations specified in the network.yaml

 

**Reviewed by**
@sownak 

 

**Linked issue**
#1422

2021-05-11 18:20 UTC, arsulegai requested changes

2021-05-12 11:15 UTC, alvaropicazo commented on platforms/hyperledger-fabric/charts/ca/templates/deployment.yaml
> +      {{ $k }}: {{ $v | quote }}
It actually works without having the annotations section in the network.yaml. You will be able to see the default annotations we already had, ie: Annotations:  helm.fluxcd.io/antecedent: salv-net:helmrelease/salv-orderer62 (example of default annotation of an orderer).

2021-05-14 18:33 UTC, arsulegai commented on platforms/hyperledger-fabric/charts/ca/templates/deployment.yaml
> +      {{ $k }}: {{ $v | quote }}
In this case specifically, I see `annotations` introduced. But then the if condition is checked for adding them. It would leave incomplete `yaml`

2021-05-20 15:12 UTC, alvaropicazo commented on platforms/hyperledger-fabric/charts/ca/templates/deployment.yaml
> +      {{ $k }}: {{ $v | quote }}
Hi Arsu, sorry for the delay. We have actually tested it and it does not create any issue in the deployment.

2021-05-21 03:01 UTC, arsulegai commented on platforms/hyperledger-fabric/charts/ca/templates/deployment.yaml
> +      {{ $k }}: {{ $v | quote }}
Sure thanks. Helm adds the annotations through it.

2021-05-21 03:01 UTC, arsulegai approved these changes

2021-05-21 07:17 UTC, merged