Feature 1317
hyperledger-labs/blockchain-automation-framework pull request #1571
Opened 2021-07-16 12:44 UTC by alvaropicazo

**Changelog**
- Updated commands for vault v2 version in every role where it was used.
- Updated charts with the correct paths required for v2 version. 

 

**Reviewed by**
@jagpreetsinghsasan 
@sownak 

 

**Linked issue**
#1317

2021-07-19 05:35 UTC, jagpreetsinghsasan commented
@alvaropicazo squash merge the commits and sign the commit, the DCO is failing

2021-07-19 05:43 UTC, jagpreetsinghsasan requested changes

2021-07-19 05:43 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/charts/invoke_chaincode/templates/invoke_chaincode.yaml
> +              SECRETPREFIX=secretsv2/data/crypto/peerOrganizations/${CREATOR_NS}/endorsers/${ns}/users/admin
I think fetching the `secret or secretv2` prefix from network.yaml is better.
Lets have a discussion around this today.

2021-07-19 05:43 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/samples/network-fabric-add-new-channel.yaml
> +        secret_path: "secretsv"
`secretsv` or `secretsv2` ?

2021-07-19 05:43 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/samples/network-fabric-add-new-channel.yaml
> +        secret_path: "secretsv"
`secretsv` or `secretsv2` ?

2021-07-19 05:43 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/samples/network-fabric-add-new-channel.yaml
> +        secret_path: "secretsv"
`secretsv` or `secretsv2` ?

2021-07-19 05:43 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/samples/network-fabric-add-new-channel.yaml
> +        secret_path: "secretsv"
`secretsv` or `secretsv2` ?

2021-07-19 05:43 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/samples/network-fabric-add-new-channel.yaml
> +        secret_path: "secretsv"
`secretsv` or `secretsv2` ?

2021-07-19 05:43 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/samples/network-fabric-add-ordererorg.yaml
> +        secret_path: "secretsv"
`secretsv` or `secretsv2` ?

2021-07-19 05:43 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/samples/network-fabric-add-ordererorg.yaml
> +        secret_path: "secretsv"
`secretsv` or `secretsv2` ?

2021-07-19 05:43 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/samples/network-fabric-add-ordererorg.yaml
> +        secret_path: "secretsv"
`secretsv` or `secretsv2` ?

2021-07-19 05:43 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/samples/network-fabric-add-ordererorg.yaml
> +        secret_path: "secretsv"
`secretsv` or `secretsv2` ?

2021-07-19 05:43 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/samples/network-fabric-add-ordererorg.yaml
> +        secret_path: "secretsv"
`secretsv` or `secretsv2` ?

2021-07-19 05:43 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/samples/network-fabric-add-ordererorg.yaml
> +        secret_path: "secretsv"
`secretsv` or `secretsv2` ?

2021-07-19 05:43 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/samples/network-fabric-add-organization.yaml
> +        secret_path: "secretsv"
`secretsv` or `secretsv2` ?

2021-07-19 05:43 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/samples/network-fabric-add-organization.yaml
> +        secret_path: "secretsv"
`secretsv` or `secretsv2` ?

2021-07-19 05:43 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/samples/network-fabric-add-organization.yaml
> +        secret_path: "secretsv"
`secretsv` or `secretsv2` ?

2021-07-19 05:43 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/samples/network-fabric-add-organization.yaml
> +        secret_path: "secretsv"
`secretsv` or `secretsv2` ?

2021-07-19 05:43 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/samples/network-fabric-add-organization.yaml
> +        secret_path: "secretsv"
`secretsv` or `secretsv2` ?

2021-07-19 05:43 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/samples/network-fabricv-add-peer.yaml
> +        secret_path: "secretsv"
`secretsv` or `secretsv2` ?

2021-07-19 05:43 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/samples/network-fabricv-add-peer.yaml
> +        secret_path: "secretsv"
`secretsv` or `secretsv2` ?

2021-07-19 05:43 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/samples/network-fabricv2-raft-add-orderer.yaml
> +        secret_path: "secretsv"
`secretsv` or `secretsv2` ?

2021-07-19 05:43 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/samples/network-fabricv2-raft.yaml
> +        secret_path: "secretsv"
`secretsv` or `secretsv2` ?

2021-07-19 05:43 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/samples/network-fabricv2-raft.yaml
> +        secret_path: "secretsv"
`secretsv` or `secretsv2` ?

2021-07-19 05:43 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/samples/network-fabricv2-raft.yaml
> +        secret_path: "secretsv"
`secretsv` or `secretsv2` ?

2021-07-19 05:43 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/samples/network-fabricv2-raft.yaml
> +        secret_path: "secretsv"
`secretsv` or `secretsv2` ?

2021-07-19 05:43 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/samples/network-fabricv2-raft.yaml
> +        secret_path: "secretsv"
`secretsv` or `secretsv2` ?

2021-07-19 05:43 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/samples/network-fabricv2.yaml
> +        secret_path: "secretsv"
`secretsv` or `secretsv2` ?

2021-07-19 05:43 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/samples/network-fabricv2.yaml
> +        secret_path: "secretsv"
`secretsv` or `secretsv2` ?

2021-07-19 05:43 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/samples/network-fabricv2.yaml
> +        secret_path: "secretsv"
`secretsv` or `secretsv2` ?

2021-07-19 05:43 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/samples/network-fabricv2.yaml
> +        secret_path: "secretsv"
`secretsv` or `secretsv2` ?

2021-07-19 05:43 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/samples/network-fabricv2.yaml
> +        secret_path: "secretsv"
`secretsv` or `secretsv2` ?

2021-07-19 05:43 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/samples/network-proxy-none.yaml
> +        secret_path: "secretsv"
`secretsv` or `secretsv2` ?

2021-07-19 05:43 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/samples/network-proxy-none.yaml
> +        secret_path: "secretsv"
`secretsv` or `secretsv2` ?

2021-07-19 05:43 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/samples/network-proxy-none.yaml
> +        secret_path: "secretsv"
`secretsv` or `secretsv2` ?

2021-07-27 15:58 UTC, sownak requested changes
wherever `vault kv get -format=yaml` has been changed to `vault kv get -field=xyz`, the following get_crypto should be updated similar to how it is done in Besu. format=yaml returned the complete secret but field will only return one specific field

2021-07-27 15:58 UTC, sownak commented on platforms/hyperledger-fabric/configuration/roles/create/crypto/orderer/tasks/orderer.yaml
> +
The following task should be changed as not vault_msp_result will have only one response. Please add a new task to get the complete msp secret and then pass that variable in vault_output for setup/get_crypto role

2021-07-27 15:58 UTC, sownak commented on platforms/hyperledger-fabric/configuration/roles/create/crypto/orderer/tasks/orderer.yaml
> +    vault kv get -field=certificate {{ vault.secret_path | default('secret') }}/crypto/{{ component_type }}Organizations/{{ component_name }}/ambassador/{{ orderer.name }}
same comment as above for the get_ambassador_crypto role

2021-07-27 15:59 UTC, sownak commented
Also, get merge latest from vaultv2 so that the Besu files do not reappear

2021-08-09 09:15 UTC, sownak approved these changes

2021-08-09 09:15 UTC, merged