[shared] create git actions to build baf-build image and push to dockerhub
hyperledger-labs/blockchain-automation-framework pull request #1632
Opened 2021-08-18 12:46 UTC by pppazos

Signed-off-by: Jose Pazos <pppazos@gmail.com>

**Changelog**
- Add git action to build baf-build image

 

**Reviewed by**
@pppazos

 

**Linked issue**
#743

2021-08-18 15:59 UTC, sownak requested changes

2021-08-19 06:05 UTC, pppazos commented on .github/workflows/docker_build.yml
> +        tags: ${{ secrets.DOCKERHUB_USERNAME }}/baf-build:latest
updated to hyperledgerlabs.  Just created with variable so is easier to test/reuse in cloned repos.

2021-08-19 06:07 UTC, pppazos commented on .github/workflows/docker_build.yml
> +        tags: ${{ secrets.DOCKERHUB_USERNAME }}/baf-build:tci.jdk8
my bad. used for a test and not removed after. fixed to be jdk8

2021-08-19 08:30 UTC, sownak approved these changes

2021-08-19 08:30 UTC, merged