[besu] added gcp-storageclass
hyperledger-labs/blockchain-automation-framework pull request #1643
Opened 2021-08-31 09:43 UTC by Roshan13046

**Changelog**
- Add gcp-storageclass
- Update main.yml file to add an entry

 

**Reviewed by**
@jagpreetsinghsasan 
@sownak 

 

**Linked issue**
#1295

2021-08-31 10:14 UTC, sownak requested changes

2021-08-31 10:14 UTC, sownak commented on docs/source/operations/adding_new_org_besu.md
> +    genesis: "/home/roshanpkraut/project/blockchain-automation-framework/build/besu_genesis"   # Location where genesis file will be fetched
don't commit personalised changes

2021-08-31 10:14 UTC, sownak commented on platforms/hyperledger-besu/charts/node_tessera/templates/deployment.yaml
> +          tail -f /dev/null
this is not to be committed

2021-08-31 10:14 UTC, sownak commented on platforms/hyperledger-besu/releases/dev/carrier-bes/reviewer_rbac.yaml
> +apiVersion: rbac.authorization.k8s.io/v1beta1
dont commit release files

2021-08-31 10:14 UTC, sownak commented on platforms/shared/configuration/site.yaml
> +  # - import_playbook: network-schema-validator.yaml
should not be commented

2021-08-31 15:31 UTC, sownak commented
Latest changes look good, only issue is that the DCO sign-off is missing, also, please squash all commits to a single commit. (that should solve the DCO issue)

2021-08-31 17:29 UTC, Roshan13046 commented
> Latest changes look good, only issue is that the DCO sign-off is missing, also, please squash all commits to a single commit. (that should solve the DCO issue)

I mistakenly made the wrong changes. Trying to fix it.

2021-09-02 10:20 UTC, sownak approved these changes

2021-09-02 10:20 UTC, merged