[quorum] update certificate paths in documentation
hyperledger-labs/blockchain-automation-framework pull request #1653
Opened 2021-09-06 09:36 UTC by kaverikhaneja

Signed-off-by: Khaneja <kaveri.khaneja@accenture.com>

**Changelog**
- Updated certificates and their paths in documentation.

 

**Reviewed by**
@sownak @jagpreetsinghsasan @suvajit-sarkar 

 

**Linked issue**
#1637

2021-09-06 11:22 UTC, kaverikhaneja commented
Work in progress.

2021-09-06 13:32 UTC, sownak requested changes

2021-09-06 13:32 UTC, sownak commented on docs/source/architectureref/certificates_path_list_quorum.md
> +| secret/{{`component_ns`}}/crypto/{{ `peer_name` }}/quorum                         | db_password                   | Password for Quorum keystore     |
The description should be updated. I think this is db password

2021-09-06 13:32 UTC, sownak commented on docs/source/architectureref/certificates_path_list_quorum.md
> +| secret/{{ `component_ns` }}/crypto/{{ `node_name` }}/certs                       | rootcacertpkcs12                |  Root CA Certificate  |
Description needs to be corrected for these, all are not root ca certificate

2021-09-07 09:44 UTC, sownak approved these changes

2021-09-07 09:44 UTC, merged