[Fabric] 2.x chaincode lifecycle update
hyperledger-labs/blockchain-automation-framework pull request #998
Opened 2020-09-08 08:41 UTC by himanshulalarya

Signed-off-by: Lal <himanshu.a.lal@accenture.com>

**Changelog**
- Add Chaincode commit
- Updated Fabric 2.x lifecycle update

 

**Reviewed by**
@jagpreetsinghsasan 

 

**Linked issue**
#980

2020-09-08 09:26 UTC, sownak requested changes

2020-09-08 09:26 UTC, sownak commented on platforms/corda-ent/configuration/roles/setup/nmap/tasks/main.yml
> +# This role creates the value file for nmap
merging needs to be fixed

2020-09-08 10:13 UTC, jagpreetsinghsasan requested changes

2020-09-08 10:13 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/charts/commit_chaincode/templates/_helpers.tpl
> +{{- end }}
Add newline

2020-09-08 10:13 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/charts/install_chaincode/templates/install_chaincode.yaml
> +          value: "{{ $.Values.metadata.network.version}}"
Make this variable from {{ VAR}} to {{ VAR }}

2020-09-08 10:13 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/charts/install_chaincode/templates/install_chaincode.yaml
> +            echo "2.x cmd executed"
change this to echo "Chaincode installed for Fabric 2.x"

2020-09-08 10:13 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/charts/install_chaincode/templates/install_chaincode.yaml
> +            echo "Inside 2.x chaincode"
Change this echo to something meaningful

2020-09-08 10:13 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/charts/install_chaincode/templates/install_chaincode.yaml
> +            echo "Inside 1.4 chaincode"
Change this echo to something meaningful

2020-09-08 10:13 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/charts/install_chaincode/templates/install_chaincode.yaml
> +            echo ${NETWORK_VERSION}
Remove this

2020-09-08 10:13 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/charts/install_chaincode/templates/install_chaincode.yaml
> +            echo "1.4 cmd executed"
Change this to echo "Chaincode install for Fabric v.1.4.4"

2020-09-08 10:13 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/roles/create/chaincode/commit/tasks/main.yaml
> +    loop_var: participant
Add newline

2020-09-08 10:13 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/roles/create/orderers/vars/main.yaml
> +  2.2.0: 0.4.18
Add newline

2020-09-08 10:13 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/roles/helm_component/templates/commit_chaincode_job.tpl
> +      name: {{ item.channel_name | lower }}
Add newline

2020-09-08 10:13 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/samples/network-fabric-add-organization.yaml
> +            lang: "golang"  # The language in which the chaincode is written ( golang/ java/ nodejs)
Dont put nodejs as an option until we have it

2020-09-08 10:14 UTC, jagpreetsinghsasan commented
Make sure to always squash and merge all commits into 1

2020-09-09 05:46 UTC, jagpreetsinghsasan approved these changes
Just make sure to have end-to-end testing before this gets merged. The code seems fine now.

2020-09-09 09:41 UTC, sownak requested changes

2020-09-09 09:41 UTC, sownak commented on platforms/hyperledger-fabric/charts/invoke_chaincode/templates/invoke_chaincode.yaml
> +          {{ if eq  $.Values.metadata.network.version "1.4.4" }}
why hardcoded to 1.4.4?

2020-09-09 09:41 UTC, sownak commented on platforms/hyperledger-fabric/configuration/roles/delete/flux_releases/meta/main.yaml
> +        version: "v2.14.1"
need to be removed

2020-09-09 09:41 UTC, sownak commented on platforms/hyperledger-fabric/configuration/roles/helm_component/templates/install_chaincode_job.tpl
> +      lang: {{ component_chaincode.lang }}
if this fails when lang does not exist in network.yaml, then that needs to be corrected.

2020-09-09 09:42 UTC, sownak commented
@jagpreetsinghsasan Please resolve conversation after checking the updates

2020-09-10 07:27 UTC, jagpreetsinghsasan approved these changes

2020-09-10 08:31 UTC, sownak approved these changes

2020-09-10 08:31 UTC, sownak commented
Approved, but will be merged after current release.

2020-09-10 08:33 UTC, merged